language: python

addons:
  apt:
    packages:
    - unzip

branches:
  only:
    - master

cache:
  - pip
  - testing/cache

env:
  global:
  - TF_VAR_build_number=${TRAVIS_JOB_NUMBER/./-}
  - TERRAFORM_VERSION=0.7.0
  matrix:
  # These providers have a full battery of Terraform+Ansible tests
  - PROVIDER=aws
  - PROVIDER=do
  - PROVIDER=gce
  # These providers are only linted using `terraform plan`, and have no secrets
  # Secrets are available for CLC, but the build times out.
  - PROVIDER=clc
  - PROVIDER=softlayer
  - PROVIDER=triton

install:
  - eval $(ssh-agent)
  - python testing/travis.py install

before_script:
  - export TERRAFORM_FILE=testing/terraform/${PROVIDER}.tf

script:
  - python testing/travis.py script
  - python testing/travis.py health_checks

after_script: python testing/travis.py after_script
