---
- name: set logrotate interval to daily
  sudo: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^weekly'
    line: "daily"
    backrefs: yes
  tags:
    - logrotate

- name: set logrotate retention period to 7 days
  sudo: yes
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: '^rotate 4'
    line: "rotate 7"
    backrefs: yes
  tags:
    - logrotate

- name: copy component logrotate configurations
  become: yes
  copy:
    src: "{{ item.component }}"
    dest: "/etc/logrotate.d/{{ item.component }}"
    mode: 0644
    owner: root
    group: root
  when: item.when
  with_items:
    - component: mesos
      when: true
    - component: docker
      when: true
    - component: vault-ssh-helper
      when: role == 'control'
    - component: zookeeper
      when: role == 'control'
  tags:
    - docker
    - logrotate
    - mesos
    - zookeeper

- name: create component archives
  sudo: yes
  file:
    path: "/var/log/{{ item.component }}/archive"
    mode: 0755
    state: directory
  when: item.when
  with_items:
    - component: mesos
      when: true
    - component: docker
      when: true
    - component: vault-ssh-helper
      when: role == 'control'
    - component: zookeeper
      when: role == 'control'
  tags:
    - docker
    - logrotate
    - mesos
    - zookeeper
