---
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart traefik
  sudo: yes
  command: systemctl restart traefik

- name: update-ca-trust
  sudo: yes
  command: update-ca-trust
