---
- name: generate consul config for NodePort services
  sudo: yes
  template:
    src: nodeport.json.j2
    dest: /etc/consul/nodeport.json
  notify:
    - reload consul
  tags:
    - node
    - kubernetes

- name: create fluentd pod
  sudo: yes
  copy:
    src: fluentd-es.yaml
    dest: "{{ kube_manifest_dir }}/fluentd-es.yaml"
  when: enable_logging
  tags:
    - addons
    - logging
    - kubernetes
